# Generated by Django 4.1 on 2022-09-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='profesion',
            new_name='cursoA',
        ),
    ]
