# Generated by Django 4.1 on 2022-09-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0002_delete_entregable_rename_profesion_profesor_cursoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='cursoA',
        ),
    ]
